import { Module, OnModuleInit } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { KpiMaintenanceController } from './controllers/kpi-maintenance.controller';
import { KpiMaintenanceService } from './services/kpi-maintenance.service';
import {
  AlertaMantenimientoEntity,
  AnalisisLubricanteDetalleEntity,
  AnalisisLubricanteEntity,
  BitacoraDiariaEntity,
  BodegaEntity,
  ControlComponenteEntity,
  ConsumoRepuestoEntity,
  CronogramaSemanalDetalleEntity,
  CronogramaSemanalEntity,
  EntregaMaterialDetEntity,
  EntregaMaterialEntity,
  EquipoComponenteEntity,
  EquipoEntity,
  EquipoTipoEntity,
  EstadoEquipoCatalogoEntity,
  EstadoEquipoEntity,
  EventoProcesoEntity,
  EventoEquipoEntity,
  FallaCatalogoEntity,
  KardexEntity,
  LecturaEquipoEntity,
  LocationEntity,
  MarcaEntity,
  LubricacionPuntoEntity,
  MovimientoInventarioDetEntity,
  MovimientoInventarioEntity,
  PlanMantenimientoEntity,
  PlanTareaEntity,
  ProductoEntity,
  ProcedimientoActividadEntity,
  ProcedimientoPlantillaEntity,
  ProgramacionMensualDetalleEntity,
  ProgramacionMensualEntity,
  ProgramacionPlanEntity,
  ReporteCombustibleEntity,
  ReporteOperacionDiariaEntity,
  ReporteOperacionDiariaUnidadEntity,
  ReservaStockEntity,
  StockBodegaEntity,
  WorkOrderAdjuntoEntity,
  WorkOrderEntity,
  WorkOrderStatusHistoryEntity,
  WorkOrderTareaEntity,
} from './entities/kpi-maintenance.entity';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      EquipoEntity,
      BitacoraDiariaEntity,
      AlertaMantenimientoEntity,
      EstadoEquipoEntity,
      EstadoEquipoCatalogoEntity,
      EventoProcesoEntity,
      EquipoTipoEntity,
      EventoEquipoEntity,
      EquipoComponenteEntity,
      FallaCatalogoEntity,
      LecturaEquipoEntity,
      LubricacionPuntoEntity,
      ProcedimientoPlantillaEntity,
      ProcedimientoActividadEntity,
      AnalisisLubricanteEntity,
      AnalisisLubricanteDetalleEntity,
      CronogramaSemanalEntity,
      CronogramaSemanalDetalleEntity,
      ReporteOperacionDiariaEntity,
      ReporteOperacionDiariaUnidadEntity,
      ReporteCombustibleEntity,
      ControlComponenteEntity,
      PlanMantenimientoEntity,
      PlanTareaEntity,
      ProgramacionPlanEntity,
      ProgramacionMensualEntity,
      ProgramacionMensualDetalleEntity,
      WorkOrderEntity,
  WorkOrderStatusHistoryEntity,
      WorkOrderStatusHistoryEntity,
      ConsumoRepuestoEntity,
      StockBodegaEntity,
      BodegaEntity,
      MarcaEntity,
      ProductoEntity,
      ReservaStockEntity,
      EntregaMaterialEntity,
      EntregaMaterialDetEntity,
      MovimientoInventarioEntity,
      MovimientoInventarioDetEntity,
      KardexEntity,
      WorkOrderTareaEntity,
      WorkOrderAdjuntoEntity,
      LocationEntity,
    ]),
  ],
  controllers: [KpiMaintenanceController],
  providers: [KpiMaintenanceService],
})
export class KpiMaintenanceModule implements OnModuleInit {
  constructor(private readonly service: KpiMaintenanceService) {}
  onModuleInit() {
    void this.service.seedEstadosCatalogo();
  }
}
